name: Rules-Rulea
main: NurAzliYT\Rules\Main
version: 1.0.0
api: 4.0.0
author: NurAzliYT
description: "Open Rules No UI"

commands:
rules: # command
permission: rules.command
description: "Open Rules No UI"


permissions:
rules.command:
default: true
